//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class HotKey : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotKey defaultInstance = ((HotKey)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotKey())));
        
        public static HotKey Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string 交接班_交接班_1 {
            get {
                return ((string)(this["交接班_交接班_1"]));
            }
            set {
                this["交接班_交接班_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string 新增会员_新增会员_1 {
            get {
                return ((string)(this["新增会员_新增会员_1"]));
            }
            set {
                this["新增会员_新增会员_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public string 查看会员资料_查看会员资料_1 {
            get {
                return ((string)(this["查看会员资料_查看会员资料_1"]));
            }
            set {
                this["查看会员资料_查看会员资料_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public string 销售单据_销售单据_1 {
            get {
                return ((string)(this["销售单据_销售单据_1"]));
            }
            set {
                this["销售单据_销售单据_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+A")]
        public string 系统设置_系统设置_1 {
            get {
                return ((string)(this["系统设置_系统设置_1"]));
            }
            set {
                this["系统设置_系统设置_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+D")]
        public string 单品删除_单品删除_1 {
            get {
                return ((string)(this["单品删除_单品删除_1"]));
            }
            set {
                this["单品删除_单品删除_1"] = value;
            }
        }
    }
}
